# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "GeoNode Summit 2018"
email: "summit@ithacaweb.org"
description: "Website of the 2018 GeoNode Summit"
baseurl: ""
url: http://summit.geonode.org
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-113363726-1" #Summit Tracking ID
googleAnalyticsSiteUrl: "geonode.github.io" #TODO!
siteVerification: "N/A" #TODO!

# Organizer Info
organizerName: "ITHACA"
organizerAlternateName: "Information Technology for Humanitarian Assistance, Cooperation and Action"
organizerDescription: "The non-profit association ITHACA is a center of applied research devoted to support humanitarian activities in response to natural disasters by means of remote sensing techniques."
organizerEmail: "summit@ithacaweb.org"
organizerLogo: "/img/organizers/ithaca.jpg"
organizerLink: "http://www.ithacaweb.org"

# Head
metaKeywords: "event, summit, geonode, open source, programming, maps, developers, politecnico, torino, django, geoserver, postgis"
twitterAccount: "@GeoNode"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/about/", text: "About"}
 - {permalink: "/logistics/", text: "Logistics"}
bottomNavigationLinks:
 - {link: "http://bit.ly/2rzWEeb", text: "Become a speaker!"}
rightNavigationButtons:
 - {link: "http://bit.ly/2rzWEeb", text: "Become a speaker!"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GeoNode <typeout> Summit 2018"
eventDate: "Torino, Italy | March 26 - 28, 2018"
typeoutTextValues: '"", "Dev", "Users", "World"'
typeoutFallback: ""
heroButtons:
 - {link: "http://bit.ly/2rzWEeb", text: "Become a speaker!"}
 - {permalink: "/#register", text: "Register"}

# About Block
aboutTitle: "About GeoNode Summit"
aboutSubTitle: "Join us for a 3-day packed event to learn and contribute to GeoNode!"
aboutBlock:
 - {title: "Presentations", image: "conference.jpg", text: "The GeoNode event of the year with awesome speakers and lots of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Improve your knowledge of GeoNode with workshops held by core developers aimed at users and developers!" }
 - {title: "Roadmapping", image: "roadmapping.jpg", text: "One full day for an open discussion on the future of GeoNode." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "50", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "20", specialCharacter: "+", info: "hours", detail: "of GeoNode full immersion"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from everywhere"}
 - {count: "2", specialCharacter: "", info: "workshops", detail: "for users and developers"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Key speakers and facilitators"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "SiTI-ITHACA"
eventLocationLink: "http://www.ithacaweb.org/"
eventStreetAddress: "Corso Castelfidardo 30/a"
eventAddressLocality: "Torino"
eventAddressLocalityRegion: "Piemonte"
eventPostalCode: "10129"
eventAddressCountry: "Italy"
eventStartTime: "2018-03-26T09:00"
eventDoorTime: "08:30"
eventEndTime: "2018-03-28T18:00"
eventPlaceCoordinates: "45.06568, 7.65967"
mapCenterCoordinates: "45.06568, 7.65967"
mapMobileCenterCoordinates: "45.06568, 7.65967"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "SiTI/ITHACA"
venueFeatures: ["One Theatre", "One Conference Room", "Two Meeting Rooms"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "geonode"
twitterFeed: "#"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "#"
subscribeInfo: "Registration will be open until around mid March."

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=GeoNode", icon: "twitter"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://geonode.org", text: "GeoNode"}
   - {link: "http://https://www.osgeo.org", text: "OSGeo"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:summit@ithacaweb.org", text: "summit@ithacaweb.org"}
 -
  title: "FAQ"
  links:
   - {permalink: "/blog/how-to-get-to-the-venue/", text: "How to get to the venue"}
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: ""

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About"
aboutUs: "The Summit 2018 brings together the community of users, developers and stakeholders of GeoNode, the popular open source geospatial content management system.
<br/><br/>Join us for a 3-day packed event to learn and contribute to GeoNode!<br/><br/>

GeoNode is a web-based Spatial Data Infrastructure (SDI) that enables sharing and collaborating on geospatial data. Users can upload existing shapefiles, edit data, and publish finished maps.<br/>GeoNode can also host static documents, such as PDF maps. GeoNode has robust support for open standards and OGC services, which streamlines integration with other systems and existing workflows. For example, data from GeoNode can be easily downloaded as a shapefile for use in ArcMap. At its core, GeoNode is designed to be customizable and extensible.<br/><br/>
GeoNode is used throughout the world by international organizations, non-profits, and mapping agencies for supporting activities ranging from emergency preparedness and response, disaster risk reduction, and many more. Additionally, GeoNode is supported by a rich ecosystem of commercial providers across the world who can help with training, technical support, or development of new features.<br/>
Whether your use case is wrangling thousands of layers or managing just 10 really well, GeoNode can help make your job easier."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Torino"
directionDetailsCards:
 - {title: "From the Airport", information: 'Torino Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://www.aeroportoditorino.it/en">airport website</a>.'}
 - {title: "Public Transit", information: 'Ordinary urban ticket is 1.50 â‚¬. More information about <a href="http://www.gtt.to.it/cms/en/fares">fares</a> and directions at <a href="http://www.gtt.to.it/cms/en/">GTT website</a>. The Torino Underground connects the Fermi station in Collegno through the Lingotto station in Torino. Vinzaglio is the closest station to ITHACA.'}
 - {title: "Hotels", information: 'Torino has lots of great hotels and apartments to rent. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Getting to the venue"
    links:
     - {link: "/blog/how-to-get-to-the-venue", text: "At the airport"}
     - {link: "/blog/how-to-get-to-the-venue", text: "Arriving by train"}
     - {link: "/blog/how-to-get-to-the-venue", text: "Get around Torino"}
   -
    title: "Registration"
    links:
     - {link: "#", text: "How to register"}
     - {link: "#", text: "Submit a presentation"}
   -
    title: "Attendance Details"
    links:
     - {link: "#", text: "Recommended Hotels"}
     - {permalink: "/cod/", text: "Code of Conduct"}
